#!/bin/sh

refname="$1"
oldrev="$2"
newrev="$3"

# --- Safety check
if [ -z "$GIT_DIR" ]; then
    echo "Don't run this script from the command line." >&2
    echo " (if you want, you could supply GIT_DIR then run" >&2
    echo "  $0 <ref> <oldrev> <newrev>)" >&2
    exit 1
fi

if [ -n "$1" -a -n "$2" -a -n "$3" ]; then
    for script in `find $PWD/hooks/post-receive.d -perm -100 ! -type d`
    do 
        $script "$1" "$2" "$3"
    done
else
    while read oldrev newrev refname
    do
        for script in `find $PWD/hooks/post-receive.d -perm -100 ! -type d`
        do
            $script "$refname" "$oldrev" "$newrev"
        done
    done
fi
